/*

 HUD_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : C:\Users\jschm\OneDrive\Dokumente\wind waker 2d\ww_hud.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hud_mapWidth 20
#define hud_mapHeight 2
#define hud_mapBank 0

extern unsigned char hud_map[];

/* End of HUD_MAP.H */
